const cloud=require('wx-server-sdk');const {pinyin}=require('pinyin-pro');const XLSX=require('xlsx');cloud.init({env:cloud.DYNAMIC_CURRENT_ENV});const db=cloud.database();
const names={WEDDING:'结婚',ENGAGEMENT:'订婚',BABY:'生子/满月',BIRTHDAY:'生日',LONGEVITY_BIRTHDAY:'寿宴',HOUSEWARMING:'乔迁',EDUCATION:'升学',FUNERAL:'丧事',OTHER:'其他'};
const ok=data=>({ok:true,data}),fail=message=>({ok:false,message});
const current=async openid=>(await db.collection('users').where({_openid:openid,status:'ACTIVE'}).limit(1).get()).data[0];
const own=async(c,id,openid)=>(await db.collection(c).where({_id:id,_openid:openid,deletedAt:null}).limit(1).get()).data[0];
const initial=n=>{const c=pinyin(String(n||'').trim().charAt(0),{toneType:'none'}).charAt(0).toUpperCase();return /[A-Z]/.test(c)?c:'#'};
exports.main=async e=>{const {_openid:openid}=cloud.getWXContext();try{
if(e.action==='login'){let u=await current(openid);if(!u){const now=db.serverDate(),r=await db.collection('users').add({data:{_openid:openid,nickname:'微信用户',avatarUrl:'',ledgerQuota:0,freeLedgerQuota:1,status:'ACTIVE',createdAt:now,updatedAt:now,deletedAt:null}});u={_id:r._id,nickname:'微信用户',ledgerQuota:0,freeLedgerQuota:1}}else if(u.freeLedgerQuota===undefined){await db.collection('users').doc(u._id).update({data:{freeLedgerQuota:1,updatedAt:db.serverDate()}});u.freeLedgerQuota=1}return ok(u)}
const u=await current(openid);if(!u)return fail('请先登录');
if(u.freeLedgerQuota===undefined){await db.collection('users').doc(u._id).update({data:{freeLedgerQuota:1,updatedAt:db.serverDate()}});u.freeLedgerQuota=1}
if(e.action==='me')return ok(u);
if(e.action==='updateMe'){const p=e.profile||{},nickname=String(p.nickname||'').trim().slice(0,24),avatarUrl=String(p.avatarUrl||'');if(!nickname)return fail('昵称不能为空');await db.collection('users').doc(u._id).update({data:{nickname,avatarUrl,updatedAt:db.serverDate()}});return ok(true)}
if(e.action==='listContacts')return ok((await db.collection('contacts').where({_openid:openid,deletedAt:null}).orderBy('nameInitial','asc').orderBy('name','asc').get()).data);
if(e.action==='createContact'){const c=e.contact||{};if(!String(c.name||'').trim())return fail('姓名不能为空');const r=await db.collection('contacts').add({data:{_openid:openid,name:c.name.trim().slice(0,30),relationship:String(c.relationship||'').trim(),notes:String(c.notes||'').trim(),nameInitial:initial(c.name),createdAt:db.serverDate(),updatedAt:db.serverDate(),deletedAt:null}});return ok({_id:r._id})}
if(e.action==='getContact')return ok(await own('contacts',e.id,openid));
if(e.action==='updateContact'){const c=e.contact||{};if(!await own('contacts',e.id,openid))return fail('联系人不存在');await db.collection('contacts').doc(e.id).update({data:{name:c.name.trim().slice(0,30),relationship:String(c.relationship||'').trim(),notes:String(c.notes||'').trim(),nameInitial:initial(c.name),updatedAt:db.serverDate()}});return ok(true)}
if(e.action==='getContactDetail'){const c=await own('contacts',e.id,openid);if(!c)return fail('联系人不存在');const rs=(await db.collection('gift_records').where({_openid:openid,contactId:e.id,deletedAt:null}).orderBy('eventDate','desc').get()).data;const records=rs.map(x=>({...x,eventName:x.eventType==='OTHER'?x.customEventName:names[x.eventType]}));const summary=records.reduce((s,x)=>(s[x.direction==='RECEIVE'?'received':'given']+=x.amountCents,s),{given:0,received:0});return ok({contact:c,records,summary})}
if(e.action==='deleteContact'){if(!await own('contacts',e.id,openid))return fail('联系人不存在');const now=db.serverDate();await db.collection('contacts').doc(e.id).update({data:{deletedAt:now}});const rs=(await db.collection('gift_records').where({_openid:openid,contactId:e.id,deletedAt:null}).get()).data;for(const x of rs)await db.collection('gift_records').doc(x._id).update({data:{deletedAt:now}});return ok(true)}
if(e.action==='createRecord'){const x=e.record||{},c=await own('contacts',x.contactId,openid);if(!c)return fail('联系人不存在');if(!Number.isInteger(x.amountCents)||x.amountCents<=0)return fail('金额不正确');const r=await db.collection('gift_records').add({data:{_openid:openid,contactId:c._id,contactName:c.name,direction:x.direction,amountCents:x.amountCents,eventType:x.eventType,customEventName:x.eventType==='OTHER'?x.customEventName:'',eventDate:x.eventDate,source:'MANUAL',createdAt:db.serverDate(),updatedAt:db.serverDate(),deletedAt:null}});return ok({_id:r._id})}
if(e.action==='getRecord')return ok(await own('gift_records',e.id,openid));
if(e.action==='updateRecord'){const x=e.record||{};if(!await own('gift_records',e.id,openid))return fail('记录不存在');if(!Number.isInteger(x.amountCents)||x.amountCents<=0)return fail('金额不正确');await db.collection('gift_records').doc(e.id).update({data:{direction:x.direction,amountCents:x.amountCents,eventType:x.eventType,customEventName:x.eventType==='OTHER'?x.customEventName:'',eventDate:x.eventDate,updatedAt:db.serverDate()}});return ok(true)}
if(e.action==='deleteRecord'){if(!await own('gift_records',e.id,openid))return fail('记录不存在');await db.collection('gift_records').doc(e.id).update({data:{deletedAt:db.serverDate()}});return ok(true)}
if(e.action==='getHomeSummary'){const $=db.command.aggregate,r=await db.collection('gift_records').aggregate().match({_openid:openid,deletedAt:null}).group({_id:'$direction',total:$.sum('$amountCents')}).end();let received=0,given=0;(r.list||[]).forEach(x=>{if(x._id==='RECEIVE')received=x.total||0;if(x._id==='GIVE')given=x.total||0});return ok({received,given,net:received-given})}
if(e.action==='exportExcel'){let records=[],skip=0;while(true){const page=(await db.collection('gift_records').where({_openid:openid,deletedAt:null}).orderBy('eventDate','desc').skip(skip).limit(100).get()).data;records=records.concat(page);if(page.length<100)break;skip+=100}if(!records.length)return fail('暂无可导出的往来记录');const rows=records.map((x,i)=>({'序号':i+1,'日期':x.eventDate||'','联系人':x.contactName||'','关系':x.relationship||'','事件':x.eventType==='OTHER'?(x.customEventName||'其他'):(names[x.eventType]||x.eventType||''),'收支':x.direction==='RECEIVE'?'收到':'给出','金额（元）':Number((x.amountCents/100).toFixed(2)),'记录方式':x.source==='MANUAL'?'手动记录':'高级账本'}));const sheet=XLSX.utils.json_to_sheet(rows),workbook=XLSX.utils.book_new();sheet['!cols']=[{wch:8},{wch:14},{wch:16},{wch:14},{wch:16},{wch:10},{wch:14},{wch:14}];XLSX.utils.book_append_sheet(workbook,sheet,'人情往来');const buffer=XLSX.write(workbook,{type:'buffer',bookType:'xlsx'}),stamp=new Date().toISOString().slice(0,10),cloudPath=`exports/${openid}/份子钱-人情往来-${stamp}-${Date.now()}.xlsx`,uploaded=await cloud.uploadFile({cloudPath,fileContent:buffer});return ok({fileID:uploaded.fileID,fileName:`份子钱-人情往来-${stamp}.xlsx`,count:records.length})}
if(e.action==='listRecords'){const rs=(await db.collection('gift_records').where({_openid:openid,deletedAt:null}).orderBy('eventDate','desc').limit(30).get()).data;return ok(rs.map(x=>({...x,eventName:x.eventType==='OTHER'?x.customEventName:names[x.eventType]})))}
if(e.action==='listLedgers'){const rs=(await db.collection('advanced_ledgers').where({_openid:openid,deletedAt:null}).orderBy('createdAt','desc').get()).data,freeQuota=u.freeLedgerQuota||0,paidQuota=u.ledgerQuota||0;return ok({quota:freeQuota+paidQuota,freeQuota,paidQuota,ledgers:rs.map(x=>({...x,eventName:x.eventType==='OTHER'?(x.customEventName||'其他'):names[x.eventType]}))})}
if(e.action==='getAdUnlockStatus')return fail('广告解锁已下线，请开通白银会员或黄金会员');
if(e.action==='claimAdLedgerQuota')return fail('广告解锁已下线，请开通白银会员或黄金会员');
if(e.action==='createLedgerMembershipOrder'){const plans={SILVER:{name:'白银会员',amountCents:990,ledgerQuota:1},GOLD:{name:'黄金会员',amountCents:1990,ledgerQuota:5}},plan=plans[e.planId];if(!plan)return fail('会员方案不存在');return fail(`${plan.name}支付尚未配置，请先接入微信支付 API v3 与支付成功回调。支付回调确认到账后，应为用户增加 ${plan.ledgerQuota} 本账本额度。`)}
if(e.action==='createLedger'){const x=e.ledger||{},name=String(x.name||'').trim().slice(0,40);if(!name)return fail('账本名称不能为空');let ledgerId='';await db.runTransaction(async t=>{const fresh=(await t.collection('users').doc(u._id).get()).data,free=fresh.freeLedgerQuota||0,paid=fresh.ledgerQuota||0;if(free+paid<=0)throw new Error('账本额度不足，请开通白银会员或黄金会员');const useFree=free>0,accessType=useFree?'FREE_TRIAL':'MEMBERSHIP',imageLimit=useFree?20:30,now=db.serverDate(),r=await t.collection('advanced_ledgers').add({data:{_openid:openid,userId:u._id,name,eventType:x.eventType||'WEDDING',customEventName:'',eventDate:x.eventDate,direction:x.direction||'RECEIVE',status:'ACTIVE',accessType,imageLimit,hasImportedRecords:false,ocrImageCount:0,recordCount:0,createdAt:now,updatedAt:now,deletedAt:null}});ledgerId=r._id;await t.collection('users').doc(u._id).update({data:{freeLedgerQuota:useFree?free-1:free,ledgerQuota:useFree?paid:paid-1,updatedAt:now}});await t.collection('ledger_quota_transactions').add({data:{_openid:openid,userId:u._id,changeAmount:-1,balanceAfter:free+paid-1,reason:useFree?'CREATE_FREE_TRIAL_LEDGER':'CREATE_MEMBERSHIP_LEDGER',ledgerId,createdAt:now}})});return ok({_id:ledgerId})}
if(e.action==='getLedger'){const ledger=await own('advanced_ledgers',e.id,openid);if(!ledger)return fail('账本不存在');const records=(await db.collection('gift_records').where({_openid:openid,ledgerId:e.id,deletedAt:null}).orderBy('eventDate','desc').get()).data.map(x=>({...x,eventName:x.eventType==='OTHER'?x.customEventName:names[x.eventType]}));const summary=records.reduce((s,x)=>(s[x.direction==='RECEIVE'?'received':'given']+=x.amountCents,s.count++,s),{received:0,given:0,count:0});const imageRows=(await db.collection('ledger_images').where({_openid:openid,ledgerId:e.id,deletedAt:null}).orderBy('createdAt','desc').get()).data;let images=imageRows;if(imageRows.length){const urls=await cloud.getTempFileURL({fileList:imageRows.map(x=>x.fileID)});const map=Object.fromEntries(urls.fileList.map(x=>[x.fileID,x.tempFileURL]));images=imageRows.map(x=>({...x,tempUrl:map[x.fileID]||''}))}return ok({ledger:{...ledger,eventName:ledger.eventType==='OTHER'?(ledger.customEventName||'其他'):names[ledger.eventType]},records,summary,images})}
if(e.action==='addLedgerImage'){const ledger=await own('advanced_ledgers',e.ledgerId,openid);if(!ledger)return fail('账本不存在');const limit=ledger.imageLimit||30;if((ledger.ocrImageCount||0)>=limit)return fail(`本账本最多上传 ${limit} 张图片`);await db.collection('ledger_images').add({data:{_openid:openid,userId:u._id,ledgerId:e.ledgerId,fileID:String(e.fileID||''),status:'UPLOADED',createdAt:db.serverDate(),deletedAt:null}});await db.collection('advanced_ledgers').doc(e.ledgerId).update({data:{ocrImageCount:db.command.inc(1),updatedAt:db.serverDate()}});return ok(true)}
if(e.action==='startLedgerOcr')return fail('OCR 尚未配置。请在服务端接入腾讯云 OCR SecretId/SecretKey 后启用，识别结果必须先进入待确认草稿。');
if(e.action==='batchImportLedger'){const ledger=await own('advanced_ledgers',e.ledgerId,openid);if(!ledger)return fail('账本不存在');const rows=Array.isArray(e.rows)?e.rows:[];if(!rows.length||rows.length>200)return fail('单次批量记录应为 1 至 200 条，可分多次继续导入');const now=db.serverDate();for(const row of rows){const name=String(row.name||'').trim().slice(0,30),amountCents=Number(row.amountCents);if(!name||!Number.isInteger(amountCents)||amountCents<=0)throw new Error('姓名或金额不正确');let contact=row.contactId?await own('contacts',row.contactId,openid):null;if(!contact){const matches=(await db.collection('contacts').where({_openid:openid,name,deletedAt:null}).get()).data;if(matches.length>1)throw new Error(`存在多个同名联系人“${name}”，请先选择具体联系人`);contact=matches[0];if(!contact){const cr=await db.collection('contacts').add({data:{_openid:openid,name,relationship:'',notes:'',nameInitial:initial(name),createdAt:now,updatedAt:now,deletedAt:null}});contact={_id:cr._id,name}}}await db.collection('gift_records').add({data:{_openid:openid,contactId:contact._id,contactName:contact.name,ledgerId:ledger._id,direction:ledger.direction,amountCents,eventType:ledger.eventType,customEventName:ledger.customEventName||'',eventDate:ledger.eventDate,source:'LEDGER_CONTACT_SELECT',createdAt:now,updatedAt:now,deletedAt:null}})}await db.collection('advanced_ledgers').doc(ledger._id).update({data:{hasImportedRecords:true,recordCount:db.command.inc(rows.length),updatedAt:now}});return ok({count:rows.length})}
if(e.action==='feedback'){await db.collection('feedback').add({data:{_openid:openid,content:String(e.content||'').slice(0,1000),createdAt:db.serverDate()}});return ok(true)}
if(e.action==='cancelAccount'){const now=db.serverDate();await db.collection('users').doc(u._id).update({data:{status:'DELETED',deletedAt:now}});for(const c of ['contacts','gift_records','advanced_ledgers','ledger_images']){const rs=(await db.collection(c).where({_openid:openid,deletedAt:null}).get()).data;for(const x of rs)await db.collection(c).doc(x._id).update({data:{deletedAt:now}})}return ok(true)}
return fail('未知操作')}catch(err){console.error(err);const message=String(err.message||'');if(message.includes('DATABASE_COLLECTION_NOT_EXIST')||message.includes('collection not exists')||message.includes('Db or Table not exist'))return fail('高级账本数据库尚未初始化，请先在当前云环境创建 advanced_ledgers、ledger_images、ledger_quota_transactions 三个集合，然后重新部署 api 云函数。');return fail(message||'服务异常')}};
